### ISSUE TITLE
Cant add rigs

### ISSUE THREAD

**Issue by DanielNagy** [prdatur/phpminer#13] opened 2014-02-16 14:30 UTC
Deleted my rigs.
Went to add one of my rigs,I saw a Incoming data request: test_connection

but nothing further happens, and i get a connection timed out

**Comment by nicoschtein** [comment] 2014-02-16 16:04
Did you update rpc client on rig?

N I C O

**Comment by prdatur** [comment] 2014-02-16 19:08
I have switched the connection system so you only need to provide the rpc client connection settings and no longer cgminer api + rpc. This change requires to update all rpcclients on the rig's and restart it.

**Comment by DanielNagy** [comment] 2014-02-17 00:18
i have done a fresh install, and there seems to be a bug somewhere still with adding rigs (i've emailed you a screenshot christian).
The first rig added ok.
The second rig seemed to add ok. but it could never talk to it.. the config.json showed why, there was a entry for the second rig i added, but no connection details populated. Not sure why they didnt, I had to do it manually.

**Comment by prdatur** [comment] 2014-02-22 10:10
Due to the conversation with emails, i will close this issue because we can't reproduce it. when it happens again, please create a new issue.

**Closed as completed by prdatur** 2014-02-22 10:10 UTC
